name: Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.10" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/date.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E cclassrush.sp -o ../plugins/cclassrush.smx
          ./spcomp -E cdeathrun.sp -o ../plugins/cdeathrun.smx
          ./spcomp -E ctimesten.sp -o ../plugins/ctimesten.smx
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: TF2Classic-Gamemodes-${{env.DATE_VERSION}}
          path: ./build/package